### ISSUE TITLE
electron-rebuild error

### ISSUE THREAD

**Issue by facetime88** [sofroniewn/electron-johnny-five-examples#6]
Hi,

I try to follow the installation and when running electron rebuild it said:

> An unhandled error occurred inside electron-rebuild
Unable to find parent node_modules directory, specify it via --module-dir, E.g. "--module-dir ." for the current directory

> Error: Unable to find parent node_modules directory, specify it via --module-dir, E.g. "--module-dir ." for the current directory
    at Object.<anonymous> (E:\arduino\electron-johnny-five-examples\1-led\node_modules\electron-rebuild\lib\src\cli.js:79:23)
    at next (native)
    at fulfilled (E:\arduino\electron-johnny-five-examples\1-led\node_modules\electron-rebuild\lib\src\cli.js:5:58)

I am on win 10 x64.
Thank you.

**Comment by jhoansebastianlara** [comment]
The same for me ☝️ :/

I'm on mac OS Mojave
Node v8.12.0
npm 6.4.1
